// <auto-generated />
using System;
using ControlVehicle.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControlVehicle.Infra.Database.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20260309012650_AddDriverCnh")]
    partial class AddDriverCnh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("control_vehicle")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControlVehicle.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoryCnh")
                        .IsRequired()
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasColumnType("character varying(11)");

                    b.Property<DateOnly>("DateExpiration")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Cnh")
                        .IsUnique();

                    b.ToTable("drivers", "control_vehicle");
                });

            modelBuilder.Entity("ControlVehicle.Domain.Entities.DriverCnh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasColumnType("character varying(11)");

                    b.Property<DateOnly>("DateExpiration")
                        .HasColumnType("date");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("Cnh")
                        .IsUnique();

                    b.HasIndex("DriverId")
                        .IsUnique();

                    b.ToTable("driver_cnhs", "control_vehicle");
                });

            modelBuilder.Entity("ControlVehicle.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Chassi")
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasColumnType("character varying(11)");

                    b.Property<string>("VehicleColor")
                        .IsRequired()
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("Renavam")
                        .IsUnique();

                    b.ToTable("vehicles", "control_vehicle");
                });

            modelBuilder.Entity("ControlVehicle.Domain.Entities.DriverCnh", b =>
                {
                    b.HasOne("ControlVehicle.Domain.Entities.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
