// <auto-generated />
using System;
using ControlVehicle.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControlVehicle.Infra.Database.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20260315014208_AddFuelControl")]
    partial class AddFuelControl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("control_vehicle")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControlVehicle.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoryCnh")
                        .IsRequired()
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasColumnType("character varying(11)");

                    b.Property<DateOnly>("DateExpiration")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Cnh")
                        .IsUnique();

                    b.ToTable("drivers", "control_vehicle");
                });

            modelBuilder.Entity("ControlVehicle.Domain.Entities.FuelControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InitialKm")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Liters")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("fuel_controls", "control_vehicle");
                });

            modelBuilder.Entity("ControlVehicle.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Chassi")
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasColumnType("character varying(11)");

                    b.Property<string>("VehicleColor")
                        .IsRequired()
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("Renavam")
                        .IsUnique();

                    b.ToTable("vehicles", "control_vehicle");
                });

            modelBuilder.Entity("ControlVehicle.Domain.Entities.VehicleControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FinalKm")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("InitialKm")
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("vehicle_controls", "control_vehicle");
                });

            modelBuilder.Entity("ControlVehicle.Domain.Entities.FuelControl", b =>
                {
                    b.HasOne("ControlVehicle.Domain.Entities.Driver", "Driver")
                        .WithMany("FuelControls")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlVehicle.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("FuelControls")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ControlVehicle.Domain.Entities.VehicleControl", b =>
                {
                    b.HasOne("ControlVehicle.Domain.Entities.Driver", "Driver")
                        .WithMany("Controls")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlVehicle.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Controls")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ControlVehicle.Domain.Entities.Driver", b =>
                {
                    b.Navigation("Controls");

                    b.Navigation("FuelControls");
                });

            modelBuilder.Entity("ControlVehicle.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Controls");

                    b.Navigation("FuelControls");
                });
#pragma warning restore 612, 618
        }
    }
}
